### ISSUE TITLE
Parsing errors with syntactically correct queries

### ISSUE THREAD

**Issue by RinkeHoekstra** [CLARIAH/grlc#25]
For instance in https://github.com/RinkeHoekstra/semanticweb-sparql-queries, for `14_describe.rq` and `22_sameAs_dbpedia.rq` and `23_sameAs_lodcache.rq`

**Comment by LaurensRietveld** [comment]
Can this be an encoding issue? I see some strange characters when viewing
this file via the browser :

https://github.com/RinkeHoekstra/semanticweb-sparql-queries/blob/master/23_sameAs_lodcache.rq

Gr, Laurens

________________________________
Sendt with my thumbs.
Please excuse brevity and typos

On Sep 8, 2016 17:38, "Rinke Hoekstra" <notifications@github.com> wrote:

For instance in https://github.com/RinkeHoekstra/semanticweb-sparql-queries,
for 14_describe.rq and 22_sameAs_dbpedia.rq and 23_sameAs_lodcache.rq

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CLARIAH/grlc/issues/25>, or mute the thread

**Comment by RinkeHoekstra** [comment]
Good catch... these were the result of copying from <http://yasgui.org> by the way ;-)

Query 14 still won't work though.

**Comment by albertmeronyo** [comment]
Thanks for these @RinkeHoekstra !
Your queries 22 and 23 work now, but 14 won't since grld does not support DESCRIBE (yet).

I'm opening a separate issue for this. Thanks!
