### ISSUE TITLE
bif functions in virtuoso

### ISSUE THREAD

**Issue by rapw3k** [CLARIAH/grlc#286]
Hi, 
I have been trying to use bif:contains in one of the queries, but after many different trials I was not able, neither using it in the $where nor in the $filter.
I found this commit, which seems to address this but unfortunately I cannot make it work.
https://github.com/CLARIAH/grlc/pull/179/commits/2d3cb5ea3319f895dc237073da4f1d26bb73df9d

See a simple example:  http://grlc.io/api-git/rapw3k/cybele/#/test/get_getByKeyword_2levelbif 

Can you advice how to use it ?

**Comment by c-martinez** [comment]
Hi @rapw3k,

Because `bif:` is a virtuoso specific function, it causes some issues with SPARQL syntax -- basically `bif:contains` is using a prefix which has not been defined. The way we have worked around this [in other projects](https://github.com/candYgene/queries/blob/master/getFeatureLocation.rq) is by adding a prefix:

```SPARQL
PREFIX bif: <bif:>
```

Adding this to `$prefixes` in the json should do the trick:

```json
"$prefixes": {
   ...
    "bif": "bif:"
  },
```
but it does not seem to be working (I don't know why, @pasqLisena any idea?)

I would suggest rewriting your query as a SPARQL with a `transform` decorator.

```SPARQL
#+ summary: "Retrieve all information about CYBELE datasets including the provided keyword, e.g., test, in the connected resources' label"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "test" ]
#+ method: "GET"
#+ pagination: 50
#+ transform: {
#+   "id": "?s",
#+   "metadata": {
#+     "property": "?p",
#+     "value": "?o"
#+   },
#+   "$anchor": "id"
#+ }

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX cybeleBase: <https://w3id.org/cybele/>
PREFIX bif: <bif:>

SELECT DISTINCT ?s ?p ?o
WHERE {
    ?s a dcat:Dataset.
    ?s ?p ?o.
    ?s ?p1 ?o1.
    ?o1 skos:prefLabel ?label.
    ?label bif:contains ?_keyword.
#    FILTER(STRSTARTS (str(?s), str(cybeleBase:)))
}
ORDER BY ?s
LIMIT 50
OFFSET 0
```
I commented out your filter because I don't think it was working -- I tested this query searching for `agriculture` and got some results. Can you let me know if this works for you?

**Comment by rapw3k** [comment]
Hi @c-martinez , thanks for your support.

I created a new rq file with the query and transformation you proposed above. See https://github.com/rapw3k/cybele/blob/master/getByKeyword_2level_transform.rq 

However, I still get error: http://grlc.io/api-git/rapw3k/cybele/#/test/get_getByKeyword_2level_transform 
(you can use for example "greece" as keyword)

Any idea?

**Comment by c-martinez** [comment]
Hi @rapw3k,

I think your query works just fine:
```json
[
  {
    "id": "https://w3id.org/cybele/dataset/id/2860876534623973295",
    "metadata": [
      {
        "property": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type",
        "value": "http://www.w3.org/ns/dcat#Dataset"
      },
      {
        "property": "http://purl.org/dc/terms/modified",
        "value": "2020-07-10"
      },
      {
        "property": "http://purl.org/dc/terms/issued",
        "value": "2019-10-10"
      }...
```

Just make sure to set your response content type to json:

![image](https://user-images.githubusercontent.com/7782231/93688530-bc6dc300-fac6-11ea-871f-41cb9e9c2543.png)

otherwise it cannot be transformed (and it throws an error -- that might be something to fix).

**Comment by rapw3k** [comment]
Indeed, overlooked the concept type, thanks a lot for the support!

**Comment by c-martinez** [comment]
Great -- glad it works.
