### ISSUE TITLE
grlc.io down

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/grlc#358]
It seems that grlc.io is down? (sorry if this isn't the right place to report this)

**Comment by rlzijdeman** [comment]
Hi @albertmeronyo @c-martinez I thought grlc.io was hosted at the VU, but VU says: "that the DNS record is not working (indeed, ping grlc.io says 'host not found'). Since the DNS of the VU is working, the admin doubts that the site is hosted at the VU)"

**Comment by LvanWissen** [comment]
According to the WHOIS information (http://whois.nic.io/), the domain was updated on the 19th of August and is now held by Kings College London (@albertmeronyo?). But, the name servers of the previous registrar GoDaddy are still used. 

Can anyone update the name servers and/or add some A-records to the domain over there?

**Comment by rapw3k** [comment]
Hi, I still cannot access grlc.io. Do you have any news on this?

**Comment by albertmeronyo** [comment]
Hi all, this should be resolved now. The issue was an incomplete domain transfer to a new registrar that did not update the DNS records, as some of you pointed out. Apologies for the inconvenience.

We are going to start up a list of alternative grlc public instances in the README to avoid shortages of this kind in the future.

Thanks for your patience and confidence!
