### ISSUE TITLE
Privacy: allow disabling calls to https://www.google-analytics.com/analytics.js from the grlc/src/templates/index.html file.

### ISSUE THREAD

**Issue by GenEars** [CLARIAH/grlc#373]
Dear GRLC team,
I observe that the https://github.com/CLARIAH/grlc/blob/bb1c70feea5919f399f35fe3fe08496a7950eb31/src/templates/index.html#L26 currently holds calls to https://www.google-analytics.com/analytics.js which creates privacy issues for private GRLC instances: unless blocked by Web browser's anti-tracking tools, analytics.js exports private URIs.

Options I see for addressing these are:
* enable starting GRLC with some "privacy" option that would call a /src/templates/index-private.html file that doesn't include calls to analytics.js
* update the GRLC README.md to inform users that further user-side anti-tracking configuration may be required.

**Comment by c-martinez** [comment]
Since 1 July 2023, Google changed the Analytics platform, so this would need to be updated. In the past I was of the opinion that keeping some minimal form of analytics (just counting number of visitors) would give us some insight into how much the grlc service is being used. Having said that, I don't think we are really using that data in any way at the moment, so I would be in favour of removing this completely.

@albertmeronyo , would you have any objection to that?

**Comment by c-martinez** [comment]
After discussing with @albertmeronyo , it turns out we do use the analytics (to get a rough idea of how many people use the grlc.io service). So I think have closed the PR removing analytics and will add a notice on  README.md.
