### ISSUE TITLE
Is it possible somehow to send LIMIT and OFFSET as parameters (not using paging) ?

### ISSUE THREAD

**Issue by rapw3k** [CLARIAH/grlc#379]
Hi @c-martinez 
I would like to be able to specify the LIMIT and OFFSET of the SPARQL inside the query, not automatically via the paging option, see e.g., : https://grlc.io/api-git/ILIAD-ocean-twin/api/#/test/get_Observations_test  (not working)
Is this possible somehow?
thanks

**Comment by c-martinez** [comment]
Hi @rapw3k,
Sorry for the delay in replying to your issue. I've had a quick look, and it appears it is not possible to do this. Basically, because having something like `LIMIT ?top` is invalid for SPARQL (limit should not be a SPARQL variable). Of course this would not be a problem once grlc rewrites ?_top to be a value, but because of the order in which grlc replaces variables, it runs into an issue.

@albertmeronyo  -- perhaps we should have another look at the query re-writing engine? This seems to be causing a couple of issues.

**Comment by c-martinez** [comment]
In principle I think this should be possible indeed. The real question here is on what time frame we could implement this (I know that both @albertmeronyo and I are a bit tied up with other work, but would welcome pull requests implementing these changes)

**Comment by c-martinez** [comment]
Haven't tested this, but I believe this should be possible since [v1.3.9](https://github.com/CLARIAH/grlc/releases/tag/v1.3.9). I'm closing this issue, but please re-open it if it does not work.
