### ISSUE TITLE
queries won't load

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/grlc#4]
Hi, I'm using the Clariah WP-4 queries [1], however my query doesn't show in grlc (while it is showing up in [1]. The three queries I have been experimenting with are:

- hisco_hsn_1.rq
- hisco_hsn_q.rq
- hisco_hsn_q2.rq 

hisco_hsn_1.rq is a copy of one of the canfam files and *IS* showing in grlc.
hiscio_hsn_q and q2 contain queries I made myself that are working in yasgui [2]. The difference between q and q2 is the explication of the endpoint. However, neither of them are showing up in grlc (although they thus are available in [1]).

Do you have any clue why this is the case?

[1] https://github.com/CLARIAH/wp4-queries
[2] http://yasgui.org/short/4yK2TTf6e

**Comment by albertmeronyo** [comment]
Hi @rlzijdeman,
The queries didn't parse at the grlc instance because they had missing PREFIX definitions (skos). Usually this isn't enough to make the queries crash at the endpoint, since the 'famous' prefixes are defined also there. The problem is that the grlc instance also parses them locally to extract the tag metadata, and hence they need to be correct (also prefix-wise) before shooting them against the endpoint.

So the fix was to add the missing prefixes to the queries (I'm also adding the missing ones in other queries).

I'm opening another issue to let users optionally have a prefix.txt file in their repos, where they declare all PREFIX definitions at once.

**Comment by rlzijdeman** [comment]
hi @albertmeronyo, thanks it now works like a charm! :)
