### ISSUE TITLE
Avoid clashes with other files present in repository?

### ISSUE THREAD

**Issue by Adafede** [CLARIAH/grlc#462]
Hi,

I found out (very cool!) that the repo I am using to store my queries is also listed but it looks like other files present in the repo are interfering, see http://grlc.io/api-git/adafede/sparql/swagger.

Would you have any suggestions on how to handle such cases? Should yml/json config files used for other actions be stored elsewhere ideally?

Thank you for the very nice work!

**Comment by c-martinez** [comment]
Hi @Adafede,

If I understand correctly, the issue seems to be that your queries are not listed in https://grlc.io/api-git/adafede/sparql/ , because they are in a subdir called queries? 

you can use the subdir keyword as described here: https://github.com/CLARIAH/grlc?tab=readme-ov-file#from-a-github-repository

So your queries generate this api:

https://grlc.io/api-git/adafede/sparql/subdir/queries

I hope I understood your question, and that this helps you, but please let me know if you have any further questions

**Comment by Adafede** [comment]
Oh, that makes sense, sorry did not understood the subdir part correctly, thank you!

**Comment by c-martinez** [comment]
No problem, glad it works now.
