### ISSUE TITLE
Unable to create a working repository

### ISSUE THREAD

**Issue by moissinac** [CLARIAH/grlc#52]
I've created a repository for request here
https://github.com/moissinac/sparqlQueries
then I point to
http://grlc.io/api/moissinac/sparqlQueries
As you can see, it produces an error

The only one request in my repo is a copy of one in your repo (https://github.com/CLARIAH/wp4-queries)
Can you help me?

**Comment by albertmeronyo** [comment]
Hi @moissinac , thanks for trying grlc!
There's an error in the metadata of your query; this line

# endpoint is http://dbpedia.org/sparql

should be

#+ endpoint: http://dbpedia.org/sparql

Can you correct this and try again?

**Comment by moissinac** [comment]
Corrected, same result
The request is a copy on the dbpedia.rq sample in your repo
Without the +, your default endpoint is dbpedia, and so the request must work

**Comment by albertmeronyo** [comment]
Thanks for reporting this. I've forked your repo at https://github.com/albertmeronyo/sparqlQueries and corrected some errors:

- The exact syntax of the endpoint entry must be `#+ endpoint: http://dbpedia.org/sparql` (notice the colon). If you want to use DBpedia's endpoint as per grlc's default it's better to not specify the endpoint decorator at all, since syntax errors in these decorators will make the whole parsing fail.
- The `NOW` within the `FILTER` should be a function
- Strictly speaking, projecting over a variable and an aggregation should require a `GROUP BY` clause
- `rdflib`'s SPARQL parser doesn't like `COUNT(*)` very much, so the `(COUNT(?var) AS ?c)` syntax is preferable

I realize these were all errors in our own project query repository, so apologies for that. Thanks again for reporting on it!

**Comment by moissinac** [comment]
After copying your new request, I've
http://grlc.io/api/albertmeronyo/sparqlQueries
partially working (the page ends with an error)
and, with the same request
http://grlc.io/api/moissinac/sparqlQueries
not working

(i'm really interested by your work; i'm working on similar concept and I think that your idea to disjoin API and API repository is really good)

**Comment by albertmeronyo** [comment]
Thanks for your comments @moissinac 
Both APIs work for me. If you click on the call name, you'll see a "Try it out" button that lets you to call the endpoint and execute the query.
The red "error" underneath is due to a bug in the spec generation and can be safely ignored.

**Comment by moissinac** [comment]
Now, it works for me. Perhaps, yesterday, my test get the file from a cache...???
Thanks
