### ISSUE TITLE
Problems running grlc locally

### ISSUE THREAD

**Issue by ma-garcia** [CLARIAH/grlc#78]
I am trying to run locally grlc so I followed the instructions to install it via Docker. I didn't have any problem during the installation and the application is up un running at http://localhost:8001 as it is says in the documentation. My problem is that no matter what repos I try to load, I get the same error on the screen:

`500 : <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p> http://linkeddata.dia.fi.upm.es:8001/api/albertmeronyo/lodapi/spec`

In the terminal where I run the docker-compose instruction, I get the following error:

> grlc_1  | 2017-10-26 14:08:55,655 [INFO] (server.swagger_spec) -----> Generating swagger spec for /albertmeronyo/lodapi on commit None
grlc_1  | 2017-10-26 14:08:58,363 [DEBUG] (prov.init_prov_graph) Ingesting Git2PROV output into RDF graph
grlc_1  | 2017-10-26 14:08:59,313 [INFO] (connectionpool._new_conn) Starting new HTTPS connection (1): api.github.com
grlc_1  | 2017-10-26 14:08:59,790 [DEBUG] (connectionpool._make_request) "GET /repos/albertmeronyo/lodapi HTTP/1.1" 401 83
grlc_1  | 2017-10-26 14:08:59,795 [INFO] (connectionpool._new_conn) Starting new HTTPS connection (1): api.github.com
grlc_1  | 2017-10-26 14:09:00,716 [DEBUG] (connectionpool._make_request) "GET /repos/albertmeronyo/lodapi/commits HTTP/1.1" 401 83
grlc_1  | 2017-10-26 14:09:00,721 [ERROR] (app.log_exception) Exception on /api/albertmeronyo/lodapi/spec [GET]
grlc_1  | Traceback (most recent call last):
grlc_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
grlc_1  |     response = self.full_dispatch_request()
grlc_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
grlc_1  |     rv = self.handle_user_exception(e)
grlc_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
grlc_1  |     reraise(exc_type, exc_value, tb)
grlc_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
grlc_1  |     rv = self.dispatch_request()
grlc_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
grlc_1  |     return self.view_functions[rule.endpoint](**req.view_args)
grlc_1  |   File "/home/grlc/grlc/src/server.py", line 211, in swagger_spec
grlc_1  |     swag = utils.build_swagger_spec(user, repo, sha, static.SERVER_NAME, prov_g)
grlc_1  |   File "/home/grlc/grlc/src/utils.py", line 260, in build_swagger_spec
grlc_1  |     commit_list = [c['sha'] for c in commits]
grlc_1  | TypeError: string indices must be integers

Any clue about what's going on?

I'm running grlc in an Ubuntu 16.04.3.

**Comment by albertmeronyo** [comment]
Hi @ma-garcia ! Thanks for using grlc.
It seems this is related to the access token your grlc instance uses to send requests to GitHub, since you're getting 401 responses to those.

Could you please try the following:
- Get a GitHub personal access token. You'll find them in the web interface: go to your profile, then *Settings*, then *Developer settings*, *Personal access tokens*, and *Generate new token*
- You'll get an access token string, copy it and save it somewhere safe (GitHub won't let you see it again!)
- Edit your `docker-compose.yml` or `docker-compose.default.yml` file, and paste this token as value of the environment variable GRLC_GITHUB_ACCESS_TOKEN
- Restart the container and try to generate a spec

I now see this is badly explained in the documentation, so apologies for that. Will update the docs if this fixes it. 

Thanks!

**Comment by ma-garcia** [comment]
That fixed the problem, thanks.
