### ISSUE TITLE
turtleize not used ?

### ISSUE THREAD

**Issue by c-martinez** [CLARIAH/grlc#97]
https://github.com/CLARIAH/grlc/blob/c6e1f952fa6cc2f7774c1077f74bda76e6cda07d/src/utils.py#L13-L20

Is this used? And if it is, should it do something with the `swag` object being passed in?

**Comment by albertmeronyo** [comment]
That's an empty turtle graph! :dancer: 

The original idea was to be able to return a [LDA](https://github.com/UKGovLD/linked-data-api/blob/wiki/Specification.md) compatible specification of that contained in the OpenAPI JSON.

This is from the times in which we were considering adding Linked Data features *on top* of grlc (instead of its more current role of "hiding" them). Should be safe to remove.
